[package]
name = "escdsa_public_key_note"
type = "contract"
authors = ["YashBit"]
compiler_version = ">=0.30.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.53.0", directory="noir-projects/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.53.0", directory="noir-projects/aztec-nr/authwit"}
